### ISSUE TITLE
Use with external camera

### ISSUE THREAD

**Issue by nss6planner** [patilunmesh/collision_risk_estimation#1]
Hello, I would like to use your code with d435i+yolov8 to build a probabilistic heat map of future occupancy for the dynamic obstacle of a person suitable for only displaying a heat map of the observed object, and when the pedestrian dynamically changes, the heat map is not dynamically generated accordingly, what is the reason for this. In addition, I would like to ask what needs to be modified when this code is used with an external camera in order to perfectly match the real-time generation of heat maps of future occupancy of pedestrians.

**Comment by patilunmesh** [comment]
Thanks for your patience. @nss6planner Would you please elaborate on the issue? If possible please share a screen recording or screenshot to help me better understand the problem. As for the question of what needs to be modified, the code only needs information related to detected objects tracked bounding box or tracklets in short. So the code is agnostic to the source of tracklets as long as the tracklets provide necessary information.

**Comment by patilunmesh** [comment]
I am closing this issue due to lack of response. Feel free to reopen this issue in future if you need any help in this regard.
